service: api-dicionario-FAAS

plugins:
    - serverless-dynamodb
    - serverless-offline

custom:
    stage: ${opt:stage, self:provider.stage}
    region: ${opt:region, 'us-east-1'}
    environment: ${self:custom.stage}
    tableThroughputs:
        prod: 1
        default: 1
    dynamodb:
        port: 8000
        inMemory: true
        migrate: true
        convertEmptyValues: true
    serverless-dynamodb:
        stages:
            - dev
        tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
        start:
            port: ${self:custom.dynamodb.port}
            inMemory: ${self:custom.dynamodb.inMemory}
            migrate: ${self:custom.dynamodb.migrate}
            convertEmptyValues: ${self:custom.dynamodb.convertEmptyValues}
            enableLogs: true

provider:
    name: aws
    runtime: nodejs18.x
    stage: dev
    timeout: 30

    environment:
        tableName: CsaTable
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:DescribeTable
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
    obter:
        handler: handler.getCsas
        events:
            - http:
                  path: /
                  method: get
                  cors: true
    obterUm:
        handler: handler.getcsaById
        events:
            - http:
                  path: /{id}
                  method: get
                  cors: true
    create:
        handler: handler.createCsa
        events:
            - http:
                  path: /
                  method: post
                  cors: true

# DynamoDB
resources:
    Resources:
        CsaTable:
            Type: "AWS::DynamoDB::Table"
            DeletionPolicy: Retain
            Properties:
                TableName: CsaTable
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH
                ProvisionedThroughput:
                    ReadCapacityUnits: 5
                    WriteCapacityUnits: 5
